"""add: relation between user and relation

Revision ID: 15ce4717213
Revises: None
Create Date: 2018-01-08 13:12:42.127940

"""

# revision identifiers, used by Alembic.
revision = '15ce4717213'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #  op.drop_table('sqlite_sequence')
    op.add_column('relationmodel', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('relationmodel_history', sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationmodel_history', 'user_id')
    op.drop_column('relationmodel', 'user_id')
    #  op.create_table('sqlite_sequence',
    #  sa.Column('name', sa.NullType(), nullable=True),
    #  sa.Column('seq', sa.NullType(), nullable=True)
    #  )
    ### end Alembic commands ###
