"""admin: use of sqlalchemy continuum plugin

Revision ID: 55a039732bef
Revises: 15ce4717213
Create Date: 2018-04-24 18:14:06.813663

"""

# revision identifiers, used by Alembic.
revision = '55a039732bef'
down_revision = '15ce4717213'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_history')
    op.drop_table('columnmodel_history')
    op.drop_table('meta_history')
    op.drop_table('relationmodel_history')
    #  op.drop_table('sqlite_sequence')
    op.drop_table('tablemodel_history')
    #  op.drop_column('columnmodel', 'version')
    #  op.drop_column('meta', 'version')
    #  op.drop_column('relationmodel', 'version')
    #  op.drop_column('tablemodel', 'version')
    #  op.drop_column('user', 'version')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #  op.add_column('user', sa.Column('version', sa.INTEGER(), nullable=False))
    #  op.add_column('tablemodel', sa.Column('version', sa.INTEGER(), nullable=False))
    #  op.add_column('relationmodel', sa.Column('version', sa.INTEGER(), nullable=False))
    #  op.add_column('meta', sa.Column('version', sa.INTEGER(), nullable=False))
    #  op.add_column('columnmodel', sa.Column('version', sa.INTEGER(), nullable=False))
    op.create_table('tablemodel_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('record_date', sa.DATETIME(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('changed', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    #  op.create_table('sqlite_sequence',
    #  sa.Column('name', sa.NullType(), nullable=True),
    #  sa.Column('seq', sa.NullType(), nullable=True)
    #  )
    op.create_table('relationmodel_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_date', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('columnl_id', sa.INTEGER(), nullable=True),
    sa.Column('columnr_id', sa.INTEGER(), nullable=True),
    sa.Column('tablel_id', sa.INTEGER(), nullable=True),
    sa.Column('tabler_id', sa.INTEGER(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('changed', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_table('meta_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('meta_type', sa.VARCHAR(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('record_date', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('meta_table_id', sa.INTEGER(), nullable=True),
    sa.Column('meta_column_id', sa.INTEGER(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('changed', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_table('columnmodel_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('record_date', sa.DATETIME(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('changed', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_table('user_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('changed', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    ### end Alembic commands ###
